### ISSUE TITLE
Crash with newest GIMP 2.9 version

### ISSUE THREAD

**Issue by mikhailnov** [auris/gimp-save-for-web#17]
Hello,

Save for Web plugin does not work with GIMP 2.9 development version.

**Comment by horstderheld** [comment]
it does partly
"Calling error for procedure 'file-png-get-defaults': Procedure 'file-png-get-defaults' returned no return values"
but saving as jpg/gif is still working

**Comment by prokoudine** [comment]
It crashes the file-png plug-in though.

**Comment by schumaml** [comment]
Rather simple bug in the file-png plug-in: https://bugzilla.gnome.org/show_bug.cgi?id=777403

Pushed to master, any builds made from now will fix this without changes to the save for web plug-in.

**Comment by mikhailnov** [comment]
Yes, it works, Thank you!
