### ISSUE TITLE
configure: command not found

### ISSUE THREAD

**Issue by RiccaDS** [auris/gimp-save-for-web#22]
Hi, I am with Linux Mint. I unpacked the zip file on my desktop. In the cell I cd to the unpacked directory and give the following commands:

1-sudo apt-get install libtool automake intltool libgimp2.0-dev  (works ok)
2-./configure   (--> gives command not found  <--) 

Excuse me I don't have a long experience with linux. In the downloaded folder I only see a configure.in file. Shouldn't I launch? ./configure.in 

Thank you

**Comment by auris** [comment]
If you want to make source code changes to the plugin, see HACKING file how to build it from this repository. It uses typical structure for linux project build, so there is plenty of info online.

If you want to use the plugin, simply install package with apt-get. Not sure how it is named, it may be part of larger gimp plugins package.
